import Head from 'next/head';
import Layout from '@/components/layout';
import Image from 'next/image';
import FotoPersonal from '../../public/images/profile/fotoCvSinFondo2.png';
import AnimatedText from '@/components/animatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='pb-0 flex items-center text-dark w-full  min-h-[80%]
      dark:text-light dark:bg-dark'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2 flex items-center justify-center'>
              <Image src={FotoPersonal} alt="Juan Diego Castillo" className="w-auto h-[80vh]"
               priority  sizes="(max-width:768px) 100vw, 
               (max-width:1200px) 50vw, 33vw"/>
            </div>
            <div className='pb-2 w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 '>
                <Link href="/dummy.pdf" target='_blank'
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:text-dark dark:bg-light
                hover:dark:text-light hover:dark:bg-dark hover:dark:border-light'
                download={true}
                >Resume <LinkArrow className={'w-6 ml-1'}/> </Link>
                <Link href="mailto:jdcastillodev@gmail.com" target='_blank'
                className='ml-4 text-lg font-medium capitalize text-dark underline
                dark:text-light'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-16 inline-block w-24'>
          <Image src={lightBulb} alt='Juan Diego Castillo' className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
